<a href="https://colab.research.google.com/github/Tianarandr/python-for-datascience/blob/master/SVM_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#FONCTION MATRICE DE CONFUSION, PRECISION, RAPPEL, F-MESURE
import numpy as np
#fonction sous Python qui permet de calculer la matrice de confusion à partir de deux vecteurs 𝑦 et y_estime
def comp_confmat(actuel, predicted):
    classes = np.unique(actuel) # extraire les differentes classes
    matrix = np.zeros((len(classes), len(classes))) # initializer une matrice avec des zeros
    
    for i in range(len(classes)):
        for j in range(len(classes)):
            matrix[i, j] = np.sum((actuel == classes[i]) & (predicted == classes[j]))

    return matrix

# une fonction qui calcule la précision globale.
def precision_globale(matriceDeConfusion):
    (m,n) = matriceDeConfusion.shape
    somme = matriceDeConfusion.sum()
    P = 0
    
    somme_par_row_p = 0
    precision_classe_arr = []
    somme_par_row = matriceDeConfusion.sum(1)
    
    
    for row in range(m):
        for col in range(n):
            if row == col:
                P += matriceDeConfusion[row][col]
                somme_par_row_p += matriceDeConfusion[row][col]
        
        precision_classe =  somme_par_row_p/somme_par_row[row]
        precision_classe_arr.append(precision_classe)
        somme_par_row_p = 0
    
    precision_globale = P/somme
    return precision_globale

# une fonction qui permet de calculer le rappel globale
def rappel_globale(matriceDeConfusion):
    (m,n) = matriceDeConfusion.shape
    somme = matriceDeConfusion.sum()
    P = 0
    
    somme_par_col = 0
    rappel_classe_arr = []
    somme_par_col = matriceDeConfusion.sum(0)
    
    for col in range(n):
        for row in range(m):
            if row == col:
                P += matriceDeConfusion[row][col]
                VP = matriceDeConfusion[row][col]
        
        rappel_classe =  VP/somme_par_col[col]
        rappel_classe_arr.append(rappel_classe)
        somme_par_row_p = 0
    
    rappel_globale = P/somme
    return rappel_globale

# une fonction pour calculer la F-mesure globale.
def f_mesure_globale(matrice_conf):
    precision = precision_globale(matrice_conf)
    rappel = rappel_globale(matrice_conf)
    return 2 * ((precision * rappel)/ (precision + rappel))



In [ ]:
from sklearn import datasets
import numpy as np
from sklearn.model_selection import train_test_split, cross_val_score, KFold
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix

def main():
    iris = datasets.load_iris()
    X = iris.data
    y = iris.target
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.2, random_state=5)

    #4.1 SVM pour classifier les types de fleurs de la base Iris 
    print("\n")
    print("SVM EN UTILISANT UNE BIBLIOTHEQUE :")
    classifier = SVC(kernel = 'linear', random_state = 1)
    classifier.fit(X_train, y_train)
    cv = KFold(n_splits=10, random_state=1, shuffle=True)
    precision = cross_val_score(classifier, X_train, y_train, cv=cv, scoring='precision_micro').mean()
    recall= cross_val_score(classifier, X_train, y_train, cv=cv, scoring='recall_micro').mean()
    f1 = cross_val_score(classifier, X_train, y_train, cv=cv, scoring='f1_micro').mean()
    accuracy = cross_val_score(classifier, X_train, y_train, cv=cv, scoring='accuracy').mean()

    print("Taux de bonne classification :", accuracy)
    print("Precision :", precision)
    print("Rapelle :", recall)
    print("F-mesure :", f1)

    results_b=classifier.predict(X_test)
    #4.3  la matrice de confusion.
    print("Matrice de confusion: \n",confusion_matrix(y_test,results_b))

main()






SVM EN UTILISANT UNE BIBLIOTHEQUE :
Taux de bonne classification : 0.9916666666666666
Precision : 0.9916666666666666
Rapelle : 0.9916666666666666
F-mesure : 0.9916666666666666
Matrice de confusion: 
 [[ 8  0  0]
 [ 0  9  2]
 [ 0  0 11]]
